# Generated by Django 3.2.5 on 2021-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='CSV/')),
            ],
        ),
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Files/')),
            ],
        ),
        migrations.CreateModel(
            name='headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='last_patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('bodypart', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('Sex', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=10)),
                ('BloodPressure', models.IntegerField(blank=True, null=True)),
                ('SkinThickness', models.IntegerField(blank=True, null=True)),
                ('Insulin', models.IntegerField(blank=True, null=True)),
                ('BMI', models.IntegerField(blank=True, null=True)),
                ('DiabetesPedigreeFunction', models.IntegerField(blank=True, null=True)),
                ('ChestPainType', models.CharField(blank=True, choices=[('0', 'No Pain'), ('1', 'Slight Pain'), ('2', 'Medium Pain'), ('3', 'Heavy Pain')], max_length=15, null=True)),
                ('BloodSugarBefore', models.IntegerField(blank=True, null=True)),
                ('BloodSugarAfter', models.IntegerField(blank=True, null=True)),
                ('MaximumHeartRate', models.IntegerField(blank=True, null=True)),
                ('smoking_status', models.IntegerField(blank=True, null=True)),
                ('HeartPatient', models.IntegerField(blank=True, null=True)),
                ('DiabeticPatient', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient_brain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('mri1', models.FileField(upload_to='', verbose_name='Previous/Brain/MRI')),
                ('mri2', models.FileField(upload_to='', verbose_name='Previous/Brain/MRI')),
                ('scan1', models.FileField(upload_to='', verbose_name='Previous/Brain/Scan')),
                ('scan2', models.FileField(upload_to='', verbose_name='Previous/Brain/Scan')),
            ],
        ),
        migrations.CreateModel(
            name='scanning_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('Sex', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=10)),
                ('brain', models.FileField(blank=True, null=True, upload_to='', verbose_name='Brain/')),
                ('lungs', models.FileField(blank=True, null=True, upload_to='', verbose_name='Lungs/')),
                ('stomach', models.FileField(blank=True, null=True, upload_to='', verbose_name='Stomach/')),
            ],
        ),
    ]
