# Generated by Django 3.2.5 on 2021-07-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='data_model',
        ),
        migrations.DeleteModel(
            name='file_model',
        ),
        migrations.DeleteModel(
            name='headline',
        ),
    ]
