# Generated by Django 3.2.5 on 2021-07-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210712_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='last_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.body_part')),
            ],
        ),
        migrations.DeleteModel(
            name='last_patients',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.gender'),
        ),
        migrations.AlterField(
            model_name='scanning_reports',
            name='Sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.gender'),
        ),
    ]
