# Generated by Django 3.2.5 on 2021-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210712_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='brain_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Brain/')),
            ],
        ),
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Files/')),
            ],
        ),
        migrations.CreateModel(
            name='lung_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Lungs/')),
            ],
        ),
    ]
