# Generated by Django 3.2.5 on 2021-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_brain_model_file_model_lung_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='data/')),
            ],
            options={
                'verbose_name': 'filename',
                'verbose_name_plural': 'filenames',
            },
        ),
        migrations.CreateModel(
            name='data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='CSV/')),
            ],
        ),
        migrations.CreateModel(
            name='department_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='detailed_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.IntegerField(blank=True, null=True)),
                ('coulmn_names', models.CharField(max_length=500)),
                ('personal', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploaded_file_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.IntegerField(blank=True, null=True)),
                ('output', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploading_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filecount', models.IntegerField()),
            ],
        ),
    ]
